# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dict.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_nav = QtWidgets.QFrame(self.centralwidget)
        self.frame_nav.setGeometry(QtCore.QRect(20, 30, 111, 451))
        self.frame_nav.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_nav.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_nav.setObjectName("frame_nav")
        self.pushButton = QtWidgets.QPushButton(self.frame_nav)
        self.pushButton.setGeometry(QtCore.QRect(10, 160, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_nav)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 230, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_nav)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 290, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.frame_nav)
        self.label.setGeometry(QtCore.QRect(20, 60, 72, 15))
        self.label.setObjectName("label")
        self.frame_content = QtWidgets.QFrame(self.centralwidget)
        self.frame_content.setGeometry(QtCore.QRect(150, 20, 331, 521))
        self.frame_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "词典"))
        self.pushButton_2.setText(_translate("MainWindow", "翻译"))
        self.pushButton_3.setText(_translate("MainWindow", "生词本"))
        self.label.setText(_translate("MainWindow", "我的"))
