# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.pwd_edit = QtWidgets.QLineEdit(Dialog)
        self.pwd_edit.setGeometry(QtCore.QRect(120, 150, 211, 41))
        self.pwd_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd_edit.setObjectName("pwd_edit")
        self.pwd_label = QtWidgets.QLabel(Dialog)
        self.pwd_label.setGeometry(QtCore.QRect(50, 150, 72, 15))
        self.pwd_label.setObjectName("pwd_label")
        self.name_edit = QtWidgets.QLineEdit(Dialog)
        self.name_edit.setGeometry(QtCore.QRect(120, 60, 211, 41))
        self.name_edit.setObjectName("name_edit")
        self.login_btn = QtWidgets.QPushButton(Dialog)
        self.login_btn.setGeometry(QtCore.QRect(110, 230, 93, 28))
        self.login_btn.setObjectName("login_btn")
        self.regi_btn = QtWidgets.QPushButton(Dialog)
        self.regi_btn.setGeometry(QtCore.QRect(230, 230, 93, 28))
        self.regi_btn.setObjectName("regi_btn")
        self.name_label = QtWidgets.QLabel(Dialog)
        self.name_label.setGeometry(QtCore.QRect(50, 70, 72, 15))
        self.name_label.setObjectName("name_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pwd_edit.setToolTip(_translate("Dialog", "密码必须包括英文字母、数字、特殊符号"))
        self.pwd_label.setText(_translate("Dialog", "密码"))
        self.name_edit.setToolTip(_translate("Dialog", "请输入6-10位的账号"))
        self.login_btn.setText(_translate("Dialog", "登录"))
        self.regi_btn.setText(_translate("Dialog", "注册"))
        self.name_label.setText(_translate("Dialog", "账号"))
