# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(723, 383)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect(350, 250, 93, 28))
        self.login_btn.setObjectName("login_btn")
        self.regi_btn = QtWidgets.QPushButton(self.centralwidget)
        self.regi_btn.setGeometry(QtCore.QRect(470, 250, 93, 28))
        self.regi_btn.setObjectName("regi_btn")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(140, 70, 72, 15))
        self.name_label.setObjectName("name_label")
        self.pwd_label = QtWidgets.QLabel(self.centralwidget)
        self.pwd_label.setGeometry(QtCore.QRect(140, 150, 72, 15))
        self.pwd_label.setObjectName("pwd_label")
        self.name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_edit.setGeometry(QtCore.QRect(350, 60, 211, 41))
        self.name_edit.setObjectName("name_edit")
        self.pwd_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.pwd_edit.setGeometry(QtCore.QRect(350, 150, 211, 41))
        self.pwd_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd_edit.setObjectName("pwd_edit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 723, 26))
        self.menubar.setObjectName("menubar")
        self.help_menu = QtWidgets.QMenu(self.menubar)
        self.help_menu.setObjectName("help_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.about_action = QtWidgets.QAction(MainWindow)
        self.about_action.setObjectName("about_action")
        self.help_action = QtWidgets.QAction(MainWindow)
        self.help_action.setObjectName("help_action")
        self.help_menu.addAction(self.about_action)
        self.help_menu.addAction(self.help_action)
        self.menubar.addAction(self.help_menu.menuAction())

        self.retranslateUi(MainWindow)
        self.regi_btn.clicked.connect(MainWindow.showMaximized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "欢迎来到的德莱联盟！"))
        self.login_btn.setText(_translate("MainWindow", "登录"))
        self.regi_btn.setText(_translate("MainWindow", "注册"))
        self.name_label.setText(_translate("MainWindow", "账号"))
        self.pwd_label.setText(_translate("MainWindow", "密码"))
        self.name_edit.setToolTip(_translate("MainWindow", "请输入6-10位的账号"))
        self.pwd_edit.setToolTip(_translate("MainWindow", "密码必须包括英文字母、数字、特殊符号"))
        self.help_menu.setTitle(_translate("MainWindow", "帮助(&F)"))
        self.about_action.setText(_translate("MainWindow", "关于"))
        self.about_action.setShortcut(_translate("MainWindow", "F4"))
        self.help_action.setText(_translate("MainWindow", "使用帮助"))
