# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(723, 383)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect(350, 250, 93, 28))
        self.login_btn.setObjectName("login_btn")
        self.regi_btn = QtWidgets.QPushButton(self.centralwidget)
        self.regi_btn.setGeometry(QtCore.QRect(470, 250, 93, 28))
        self.regi_btn.setObjectName("regi_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 70, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 150, 72, 15))
        self.label_2.setObjectName("label_2")
        self.name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_edit.setGeometry(QtCore.QRect(350, 60, 211, 41))
        self.name_edit.setObjectName("name_edit")
        self.pwd_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.pwd_edit.setGeometry(QtCore.QRect(350, 150, 211, 41))
        self.pwd_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd_edit.setObjectName("pwd_edit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 723, 26))
        self.menubar.setObjectName("menubar")
        self.menu_H = QtWidgets.QMenu(self.menubar)
        self.menu_H.setObjectName("menu_H")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.actionshi = QtWidgets.QAction(MainWindow)
        self.actionshi.setObjectName("actionshi")
        self.menu_H.addAction(self.actionabout)
        self.menu_H.addAction(self.actionshi)
        self.menubar.addAction(self.menu_H.menuAction())

        self.retranslateUi(MainWindow)
        self.regi_btn.clicked.connect(MainWindow.showMaximized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "欢迎来到的德莱联盟！"))
        self.login_btn.setText(_translate("MainWindow", "登录"))
        self.regi_btn.setText(_translate("MainWindow", "注册"))
        self.label.setText(_translate("MainWindow", "账号"))
        self.label_2.setText(_translate("MainWindow", "密码"))
        self.name_edit.setToolTip(_translate("MainWindow", "请输入6-10位的账号"))
        self.pwd_edit.setToolTip(_translate("MainWindow", "密码必须包括英文字母、数字、特殊符号"))
        self.menu_H.setTitle(_translate("MainWindow", "帮助(H)"))
        self.actionabout.setText(_translate("MainWindow", "关于"))
        self.actionabout.setShortcut(_translate("MainWindow", "F4"))
        self.actionshi.setText(_translate("MainWindow", "使用帮助"))
